# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'

platform :ios


target 'MNNKitDemo' do
  project './MNNKitDemo.xcodeproj'
  
    platform :ios, '8.0'
    
#    # 人脸检测
#    pod 'MNNFaceDetection', '~> 0.0.1'
#    # 手势识别
#    pod 'MNNHandGestureDetection', '~> 0.0.1'
#    # 人像分割
#    pod 'MNNPortraitSegmentation', '~> 0.0.1'
    
    
    pod 'MNNFaceDetection', :podspec=>"https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/0/f/MNNFaceDetection/0.0.1/MNNFaceDetection.podspec.json"
    pod 'MNNHandGestureDetection', :podspec=>"https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/9/e/MNNHandGestureDetection/0.0.1/MNNHandGestureDetection.podspec.json"
    pod 'MNNPortraitSegmentation', :podspec=>"https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/1/5/0/MNNPortraitSegmentation/0.0.1/MNNPortraitSegmentation.podspec.json"
    pod 'MNNKitCore', :podspec=>"https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/3/0/MNNKitCore/0.0.2/MNNKitCore.podspec.json"
    
    pod 'MNN', :podspec=>"https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/c/9/MNN/0.2.1.7/MNN.podspec.json"
    
    
    pod 'FMDB', :podspec=>"https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json"
    
    
    
    
end
